Seyahat Rehberi/Models/Sınıflar/Blog.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Management.Instrumentation;
using System.Web;

namespace Seyahat_Rehberi.Models.Sınıflar
{
    public class Blog
    {
        [Key]
        public int ID { get; set; }
        public string Baslik { get; set; }
        public DateTime Tarih { get; set; }
        public string Aciklama { get; set; }
        public string BlogImage { get; set; }

        

    }
}

Seyahat Rehberi/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Seyahat_Rehberi.Models.Sınıflar;
using PagedList;
using PagedList.Mvc;
using System.Drawing.Printing;


namespace Seyahat_Rehberi.Controllers
{
    public class BlogController : Controller


    {
        // GET: Blog
        Context c = new Context();
        BlogYorum by = new BlogYorum();



        public ActionResult Index()
        {
            //var bloglar = c.Blogs.ToList();
            by.Deger1 = c.Blogs.ToList();
            by.Deger3 = c.Blogs.OrderByDescending(x => x.ID).Take(3).ToList();
            return View(by);
        }

        public ActionResult BlogDetay(int ID)
        {
            //var blogbul = c.Blogs.Where(x=>x.ID == ID).ToList();
            by.Deger1 = c.Blogs.Where(x => x.ID == ID).ToList();
            by.Deger2 = c.Yorumlars.Where(x => x.Blogid == ID).ToList();
            return View(by);
        }
        [HttpGet]
        public PartialViewResult YorumYap(int ID)
        {
            ViewBag.deger = ID;
            return PartialView();
        }


        [HttpPost]
        public PartialViewResult YorumYap(Yorumlar y)
        {
            if (ModelState.IsValid)
            {
                c.Yorumlars.Add(y);
                c.SaveChanges();
            }
            return PartialView();
        }


    }
}

Seyahat Rehberi/Views/Blog/BlogDetay.cshtml
@model Seyahat_Rehberi.Models.Sınıflar.BlogYorum
@{
    ViewBag.Title = "BlogDetay";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<head>
    <title>Personal Blog a Blogging Category Flat Bootstarp  Responsive Website Template | Single :: w3layouts</title>
    <link href="~/web2/css/bootstrap.css" rel='stylesheet' type='text/css' />
    <link href="~/web2/css/style.css" rel='stylesheet' type='text/css' />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Personal Blog Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
	Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!----webfonts---->
    <link href='http://fonts.googleapis.com/css?family=Oswald:100,400,300,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,300italic' rel='stylesheet' type='text/css'>
    <!----//webfonts---->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <!--end slider -->
    <!--script-->


</head>
<body>
    <!---header---->
    <div class="header">

    </div>
    <!--/header-->
    <div class="single">
        <div class="container">
            <div class="col-md-8 single-main">
                <div class="single-grid">
                    @foreach (var x in Model.Deger1)
                    {
                        <img src="@x.BlogImage" alt="" style="margin-bottom:20px" />
                        <h2> @x.Baslik</h2>

                        <p>
                            @x.Aciklama
                        </p>
                    }
                </div>
                @foreach (var y in Model.Deger2)
                {
                    <ul class="comment-list">

                        <li>
                            <img src="/web2/images/avatar.png" class="img-responsive" alt="">
                            <div class="desc">
                                <p>@y.KullaniciAdi: @y.Yorum </p>
                            </div>
                            <div class="clearfix"></div>
                        </li>

                    </ul>
                }
                @Html.Action("YorumYap", "Blog")
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</body>
</html>

Seyahat Rehberi/Views/Blog/Index.cshtml
@model  Seyahat_Rehberi.Models.Sınıflar.BlogYorum

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<!DOCTYPE HTML>
<html>
<head>
    <link href="~/web2/css/bootstrap.css" rel='stylesheet' type='text/css' />
    <link href="~/web2/css/style.css" rel='stylesheet' type='text/css' />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Personal Blog Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
	Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!----webfonts---->
    <link href='http://fonts.googleapis.com/css?family=Oswald:100,400,300,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,300italic' rel='stylesheet' type='text/css'>
</head>
<body>
    <!---header---->
    <div class="header">
        <div class="container">


            <div class="clearfix"></div>

        </div>
    </div>
    <!--/header-->
    <div class="single">
        <div class="col-md-4 side-content">
            <div class="recent">
                <h3>Son Bloglar</h3>
                @foreach (var y in Model.Deger3)
                {
                    <ul>
                        <li><a href="/Blog/BlogDetay/@y.ID">@y.Baslik</a></li>
                    </ul>
                }
            </div>
        </div>
        <div class="container">
            <div class="col-md-8 single-main">
                @foreach (var x in Model.Deger1)
                {
                    <div class="single-grid">
                        <img src="@x.BlogImage" alt="" style="margin-bottom:20px" />
                        <a href="/Blog/BlogDetay/@x.ID"> @x.Baslik</a>
                        <p>
                            @x.Aciklama.Substring(0, 300)...
                        </p>
                    </div>
                    <br /><br />
                }
            </div>
        </div>


    </div>
</body>
</html>

Seyahat Rehberi/Views/Blog/YorumYap.cshtml
<div class="content-form">
    <h3>Bir Yorum Yapın.</h3>

    <form method="post">
        <input type="hidden" placeholder="ID" name="BlogID" value=" @ViewBag.deger" required />
        <input type="text" placeholder="Kullanıcı Adı" name="KullaniciAdi" required />
        <input type="text" placeholder="Mail Adresi" name="Mail" required />
        <textarea placeholder="Yorum" name="Yorum "></textarea>
        <input type="submit" value="Gönder" />
    </form>
</div>