Seyahat Rehberi/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Seyahat_Rehberi.Models.Sınıflar;

namespace Seyahat_Rehberi.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        Context c = new Context();
        public ActionResult Index()
        {
            var degerler = c.Hakkimizdas.ToList();
            return View(degerler);
        }
    }
}

Seyahat Rehberi/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<title>W3.CSS</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<body>

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />


    <!-- Sidebar -->
    <div class="w3-sidebar w3-light-grey w3-bar-block" style="width:15%">
        <h3 class="w3-bar-item">Menüler</h3>
        <a href="/Admin/Index/" class="w3-bar-item w3-button">Bloglar</a>
        <a href="/Admin/YorumListesi/" class="w3-bar-item w3-button">Yorumlar</a>
        <a href="/Admin/İletisim/" class="w3-bar-item w3-button">İletisim</a>
        <a href="/Default/Index/" class="w3-bar-item w3-button">Siteye Git</a>
        <a href="/GirişYap/LogOut/" class="w3-bar-item w3-button">Çıkış Yap</a>
    </div>

    <!-- Page Content -->
    <div style="margin-left:15%">

        <div class="w3-container w3-teal">
            <h4>Admin Yönetim Planı</h4>
        </div>


        <div class="w3-container">
            @RenderBody()
        </div>

    </div>

</body>
</html>

Seyahat Rehberi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ASP.NET Uygulamam</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Uygulama adı", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Giriş Sayfası", "Index", "Home")</li>
                    <li>@Html.ActionLink("Hakkında", "About", "Home")</li>
                    <li>@Html.ActionLink("Kişi", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ASP.NET Uygulamam</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Seyahat Rehberi/Views/Shared/_TestLayout.cshtml
@{
    Layout = null;
}

<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<head>
    <title>Free Easy-Trip Website Template | Home :: w3layouts</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" href="~/web/css/style.css" type="text/css" media="all" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="~/web/css/slider.css" rel="stylesheet" type="text/css" media="all" />
    <script src="~/web/js/jquery.min.js"></script>
    <script src="~/web/js/responsiveslides.min.js"></script>

    <script>
    // You can also use "$(window).load(function() {"
    $(function () {
      // Slideshow 1
      $("#slider1").responsiveSlides({
         auto: true,
		 nav: true,
		 speed: 500,
		 namespace: "callbacks",
      });
    });
    </script>
</head>
<body>
    <div class="header">
        <div class="wrap">
            <div class="logo"><a href="index.html"><img src="~/web/images/logo.png" alt="" /></a></div>
            <div class="con-right">
                <div class="grid1-l-img">
                    <img src="~/web/images/contact.png" alt="">
                </div>
                <div class="grid1-l-desc">
                    <p>Whatsapp : +90 (531)698 27 81</p>
                </div>
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
        </div>
    </div>
    <div class="header-bottom">
        <div class="wrap">
            <ul id="nav">
                <li><a href="/Default/Index/">Ana Sayfa</a></li>
                <li><a class="hsubs" href="/About/Index/">Hakkımızda</a></li>

                <li><a class="hsubs" href="/Blog/Index/">Blogum</a></li>
                <li><a href="/İletisim/Index/">İletisim</a></li>

            </ul>
        </div>
    </div>
    <div class="header-banner">
        <div class="wrap">
            <div class="clear"></div>
        </div>
    </div>
    <div class"content">
        @RenderBody()
    </div>
    <div class="footer-bottom">
        <div class="wrap">
            <div class="copy">
                <p>&copy;2023 Tatil-Seyahat.Tüm hakları saklıdır. | Design by <a href="http://w3layouts.com">W3Layouts</a></p>
            </div>
        </div>
    </div>
</body>
</html>